"""Controlled asset discovery provider boundary.

This module intentionally implements only deterministic, scope-safe discovery
against explicitly supplied targets. It does not perform network probing yet.
The provider establishes the execution/handoff pattern that real discovery
backends can later implement without bypassing campaign safety controls.
"""

from __future__ import annotations

from ipaddress import ip_address
from urllib.parse import urlparse

from threatlens.domain.models import Asset
from threatlens.providers.handoff import ProviderHandoff
from threatlens.providers.runtime import ExecutionContext, Provider, ProviderEvent


class DiscoveryProvider(Provider):
    """Scope-controlled discovery of already-authorized target identifiers."""

    name = "builtin-discovery"
    version = "1.0.0"

    def __init__(self, handoff: ProviderHandoff) -> None:
        self.handoff = handoff

    def execute(self, context: ExecutionContext) -> None:
        for target in context.policy.targets:
            if context.cancellation.is_set():
                context.emit(ProviderEvent("CANCELLED", "discovery cancelled"))
                return

            normalized = self._normalize_target(target)
            asset = Asset(
                canonical_id=f"{normalized[0]}:{normalized[1]}",
                asset_type=normalized[0],
                value=normalized[1],
            )
            context.emit(
                ProviderEvent(
                    "EVIDENCE",
                    "authorized discovery target normalized",
                    {"asset_id": str(asset.id), "asset_type": asset.asset_type, "value": asset.value},
                )
            )

            # The current handoff contract requires evidence before a finding;
            # discovery therefore emits inventory evidence only. No vulnerability
            # claim is generated by this provider.
            self.handoff.record_evidence(
                context,
                kind="discovery-target",
                content=asset.value,
                metadata={"asset_id": str(asset.id), "asset_type": asset.asset_type},
            )

    @staticmethod
    def _normalize_target(target: str) -> tuple[str, str]:
        value = target.strip()
        if not value:
            raise ValueError("discovery target cannot be empty")

        try:
            parsed_ip = ip_address(value)
            return ("ipv4" if parsed_ip.version == 4 else "ipv6", str(parsed_ip))
        except ValueError:
            pass

        parsed = urlparse(value if "://" in value else f"https://{value}")
        if parsed.hostname:
            scheme = parsed.scheme.lower()
            if scheme in {"http", "https"}:
                return ("url", value)
            return ("fqdn", parsed.hostname.lower().rstrip("."))

        raise ValueError(f"unsupported discovery target: {target!r}")
